version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-network

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - prometheus-network

networks:
  prometheus-network:
    driver: bridge