version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment: 
      http.host: 0.0.0.0
      transport.host: localhost
      network.host: 0.0.0.0
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" 
    volumes: 
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - graylog-network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - graylog-network
  
  graylog:
    image: graylog/graylog:4.0
    container_name: graylog
    hostname: 'graylog-server'
    depends_on: 
      - mongo
      - elasticsearch
    volumes:
      - graylog-data:/usr/share/graylog/data/journal 
    ports:
      - "9000:9000"
      - "12201:12201"
      - "12201:12201/udp"
      - "1514:1514"
      - "1514:1514/udp"
    environment: 
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog-network

volumes: 
  mongo-data:
  elasticsearch-data:
  graylog-data:

networks:
  graylog-network:
    driver: bridge