FROM maven:3.6.0-jdk-11-slim AS build
WORKDIR /workspace/app
COPY pom.xml .
COPY src src
RUN mvn clean package
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM gcr.io/distroless/java:11
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-cp", "app:app/lib/*", "-Dspring.profiles.active=docker", "br.com.cvinicius.Application"]